Repository githubschool/open-door, pull requests merged in 2021-07, with the labels that each got.

#17 Update 20-spqi.md
  _slides/20-spqi.md
Labels: documentation

#23 Updated the caption 25-1633605-Phaneendra.md
  _slides/25-1633605-Phaneendra.md
Labels: good first issue

#25 Update 21-srikisc.md for Caption
  _slides/21-srikisc.md
Labels: documentation, slides

#22 Updated the Caption for Lowell7im Slide
  _slides/12-Lowell7im.md
Labels: documentation, enhancement

#9 Update 07-1626125.md
  _slides/07-1626125.md
Labels: enhancement

#12 Update 15-kksumit.md
  _slides/15-kksumit.md
Labels: documentation, enhancement
